meta_product_name: "KiteSafe"
meta_title: "KiteSafe - Get matched to the safest spots to kite surf"
meta_description: "KiteSafe is a community driven app for beginner kitesurfers where they get matched to the best and safest spots for them to progress"
meta_image: "cover.png" # should exist in `app/assets/images/`
